### ISSUE TITLE
很棒的rpc框架，请问是否有讨论群

### ISSUE THREAD

**Issue by Meedly** [neoremind/navi#2]

**Comment by neoremind** [comment]
你好，谢谢关注，暂时还没有讨论群。我们公司内部应用稳定，一家深圳的公司随手记也是采用的这套框架。

On Wed, May 25, 2016 at 4:18 PM, Tong.Wang notifications@github.com wrote:

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/neoremind/navi/issues/2

## 

Best regards,
Xu Zhang (张旭)
